dist: trusty
language: rust
services: docker

env:
  global:
    - CRATE_NAME=pipitor
    - RUST_BACKTRACE=1

jobs:
  include:
    - env: TARGET=armv7-unknown-linux-gnueabihf
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=x86_64-apple-darwin
      os: osx
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
    - os: windows
      env: TARGET=x86_64-pc-windows-msvc

before_install: set -e
install: source ~/.cargo/env || true
before_script: set +e
script: "true"

before_deploy:
  - sh scripts/install.sh
  - sh scripts/before_deploy.sh

deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  token:
    secure: "H1vo+JBJj2d5TC+FEs0VvpENSgPy/Te4M6MK5bd1USq70eXll1axNgTt7+SDy+T0w5TqHYyq0PZNexzDIXl3XolhN2Ol6di/AnBEg/Hto4HerGjWGK+RjoPsDWrYb8fipRMqDjdRNY7tn6WcOwDXLbtVhimdT3XND0I6atnRlX9Gnv3KqC2167R711kL4+L+aKpTsiQTdljRsLl8a442UwcbUIERCnI6/v0JlMeqLIu1YaSoGX30wKbHfY3oCqV4lvKpIFM6tVCsorLT4R7tVOyUaz05W5cxGyshv5w2v1OxrxlzGfzrL/6VOyoso5qAvfzLZf4Y8xwOuzmLvRZghgPcBNnXK5GeskGOHb++2AgEY9QqGYu2zodSUwzTtMYKHZ7yZDxlPDI+g0S37jgdB7LnNCq/stKdJnczGins5GVCdZtSM8MKoARQkkV9lIYCjry9/HN74Lu8uuLbtRFRkBzlVZHNXvu9p7uCDzE9RxjaVoR6WQlSBSTMv5TKtmxbeMkPllxkH0/nPSEBFhzGfdf+9wRLt/WZ6k1/z9bcgXvFLUc3x7/mCUvxiQz8W9YSsrJSaes1bHgokhS8XqYnzH7E6k1FP4aPvA75wWk9devtw8QpBHO2A9yayZWaUPgHw/TNaeB+gcKSuG+KiTWSs2lhoWPwqh+WiR+bwbfuB7w="
  draft: true
  on:
    tags: true

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
    on_failure: never
