[target.aarch64-unknown-linux-gnu]
image = "tesaguri/pipitor:aarch64-unknown-linux-gnu"

[target.armv7-unknown-linux-gnueabihf]
image = "tesaguri/pipitor:armv7-unknown-linux-gnueabihf"

[target.x86_64-unknown-freebsd]
image = "tesaguri/pipitor:x86_64-unknown-freebsd"
