[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/tesaguri/pipitor/cross:aarch64-unknown-linux-gnu"

[target.armv7-unknown-linux-gnueabihf]
image = "ghcr.io/tesaguri/pipitor/cross:armv7-unknown-linux-gnueabihf"

[target.x86_64-unknown-freebsd]
image = "ghcr.io/tesaguri/pipitor/cross:x86_64-unknown-freebsd"
