[twitter]
# `user_id` of the account used to retrieve Tweets
user = 0
# `list_id` of the list used to backfill timeline (optional)
# Running `pipitor twitter-list-sync` will overwrite members in the list.
list = 0

[twitter.client]
key = "Your application's API key"
secret = "Your application's API secret"

[[rule]]
topics = [
    # `user_id`s of accounts to retrieve Tweets from
    783214, # @Twitter
    12, # @jack
]
# If `filter` is unspecified, the rule will match any Tweet.
filter = "regex|to|filter the|Tweets"
# `user_id` of the account to Retweet filtered Tweets.
# This can be `0`, in which case the matched Tweets won't be Retweeted.
outbox = 0

[[rule]]
topics = [
    17874544, # @TwitterSupport
]
filter = "(?i)Another filter|This regex is case insensitive"
