[websub]
host = "https://your-domain.example/websub/"
bind = "tcp://0.0.0.0:8080"

[twitter]
# `user_id` of the account used to retrieve Tweets
user = 12345
# `list_id` of the list used to backfill timeline (optional)
# Running `pipitor twitter-list-sync` will overwrite members in the list.
list.id = 123456

[twitter.client]
identifier = "Your application's API key"
secret = "Your application's API secret"

[[rule]]
topics = [
    # `user_id`s of accounts to retrieve Tweets from
    783214, # @Twitter
    12, # @jack
    # ... or Atom/RSS feed URLs.
    "https://wordpress.com/blog/feed/atom/",
]
# If `filter` is unspecified, the rule will match any Tweet.
filter = "regex|to|filter the|Tweets"
# `user_id` of the account to Retweet filtered Tweets. This can also be a list of multiple IDs.
outbox = 12345

[[rule]]
topics = [
    17874544, # @TwitterSupport
]
filter = "(?i)Another filter|This regex is case insensitive"
exclude = "excluding Tweets that match this regex"
# `outbox` can be an empty list, in which case the matched Tweets won't be Retweeted.
outbox = []
