name: Build containers

on: workflow_dispatch

jobs:
  build:
    name: Build container
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
    steps:
    - uses: actions/checkout@v2
    - name: Log into registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: docker/${{ matrix.target }}
        push: true
        tags: ghcr.io/tesaguri/pipitor/cross:${{ matrix.target }}
